services:
  _defaults:
    autowire: true
    autoconfigure: true
  Kiwi\Contao\BootstrapBundle\EventListener\LoadDataContainerListener: ~
  Kiwi\Contao\BootstrapBundle\EventListener\GeneratePageListener: ~
  Kiwi\Contao\BootstrapBundle\EventListener\AlterResponsiveValues: ~